wakeword_detection:
  enabled: true
  access_key: ""  # Din Porcupine access key från https://console.picovoice.ai/ (eller använd .env)
  keyword: "porcupine"  # Inbyggda: porcupine, alexa, computer, jarvis
  sensitivity: 0.5
  model_path: ""  # Path till custom .ppn fil (optional)

stt:
  enabled: true
  model_size: "base"  # Model size: tiny, base, small, medium, large (base recommended for Raspberry Pi)
  language: "sv"  # Swedish language

tts:
  enabled: true
  engine: "piper"  # Piper TTS engine
  language: "sv"  # Swedish language
  voice: "sv_SE-nst-medium"  # Swedish voice model
  model_path: "models/sv_SE-nst-medium.onnx"  # Path to Piper model
  config_path: "models/sv_SE-nst-medium.onnx.json"  # Path to model config

mqtt:
  broker: "7dab69000883410aba47967fb078d6d9.s1.eu.hivemq.cloud"  # HiveMQ Cloud broker
  port: 8883
  topic: "genio/agent"
  client_id: "genio_ai"
  username: ""  # Din HiveMQ username
  password: ""  # Din HiveMQ password
  use_tls: true  # HiveMQ kräver TLS/SSL

logging:
  level: "INFO"
  file: "logs/genio_ai.log"