wakeword_detection:
  enabled: true
  access_key: "YOUR_PORCUPINE_ACCESS_KEY_HERE"  # MÅSTE ÄNDRAS! Hämta gratis key från https://console.picovoice.ai/
  keyword: "porcupine"  # Inbyggda: porcupine, alexa, computer, jarvis
  sensitivity: 0.5
  model_path: ""  # Path till custom .ppn fil (optional)

stt:
  enabled: true
  model_size: "base"  # Model size: tiny, base, small, medium, large (base recommended for Raspberry Pi)
  language: "sv"  # Swedish language

audio:
  record_seconds: 5  # Duration to record after wake word detection (in seconds)

tts:
  enabled: true
  engine: "piper"  # Piper TTS engine
  language: "sv"  # Swedish language
  voice: "sv_SE-nst-medium"  # Swedish voice model
  model_path: "models/sv_SE-nst-medium.onnx"  # Path to Piper model
  config_path: "models/sv_SE-nst-medium.onnx.json"  # Path to model config

mqtt:
  broker: "YOUR_MQTT_BROKER_ADDRESS"  # MÅSTE ÄNDRAS! Exempel: xxx.s1.eu.hivemq.cloud (för HiveMQ Cloud)
  port: 8883  # 8883 för TLS/SSL, 1883 för vanlig MQTT
  topic: "genio/agent"
  client_id: "genio_ai"
  username: "YOUR_MQTT_USERNAME"  # MÅSTE ÄNDRAS! Ditt MQTT användarnamn
  password: "YOUR_MQTT_PASSWORD"  # MÅSTE ÄNDRAS! Ditt MQTT lösenord
  use_tls: true  # true för säker anslutning (rekommenderas), false för osäker

logging:
  level: "INFO"
  file: "logs/genio_ai.log"